# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "12203900bc4650c64307c4a1b47d1fc1"
name = "Ai-App"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_draft_orders,read_inventory,read_locations"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
